### PR TITLE
adding templating for service commands

### PR DESCRIPTION
**Pull request by wraithan**
This allows people on other operating systems to use the service commands as well by customizing the env.service_command_template.

For example, Arch Linux keeps all services in `/etc/rc.d/` and in recent times, using the`rc.d` command is favored over calling the scripts from the services directory. Simply changing `service_command` to use `invoke-rc.d` wouldn't have been enough because it has different argument order.

```
invoke-rc.d nginx restart
```

vs

```
rc.d restart nginx
```

What I've done solves the problem of specifying the dir, or service script in the most general way possible. Allowing most any distro I know of to us this.

I did no add documentation for this as not much else is documented yet, so I'd be shooting in the dark by trying to add it.

### CODE REVIEW

**Comment by mlavin** [comment]
I like this idea. I think my only suggestion would be to handle this more like how I've handled `ARGYLE_TEMPLATE_DIRS`: https://github.com/mlavin/argyle/blob/develop/argyle/base.py#L41 Two main points:
1.) Since we are adding things to the global fabric environment I'd like to keep them prefixed (sort of a Django settings-like convention).
2.) I'm not a fan of having the import statement having the side-effect of changing the `env`. I rather look for it in `service_command` and if it doesn't exist use a default.

The docs need work but that's on me. I'm going to try to get some work in on this today.

**Comment by wraithan** [comment]
Ah, I didn't see you already had a pattern for this. I'll modify the
code to match this pattern.

On Sun, Oct 16, 2011 at 8:07 AM, Mark Lavin
reply@reply.github.com
wrote:

**Comment by wraithan** [comment]
Ok, this now follows the same pattern that you used.

**Comment by mlavin** [comment]
Merged. Thanks for the contribution!

**Pull request merged**
